### ISSUE TITLE
Regarding code execution in python 3.6

### ISSUE THREAD

**Issue by sumith97** [nazmiasri95/Face-Recognition#10]
Bro the project was amazing just there should be some changes in training.py to make the training perfectly

I just have to change some code i.e del imagePaths[0] for proper functioning.

I'm gonna add new functionality i.e
before taking the datasets I would ask the user to enter name

**Comment by nazmiasri95** [comment]
Sure, you can do that. Sorry for the late reply. Now I have put `requirements.txt` in case you have dependencies problem. 

If you don't mind to attach you github link or let's discuss about this further
