### ISSUE TITLE
HAVING A PROBLEM

### ISSUE THREAD

**Issue by mohit03031999** [nazmiasri95/Face-Recognition#11]
error                                     Traceback (most recent call last)
<ipython-input-1-b323c9dda86b> in <module>()
     44 
     45     # Convert the captured frame into grayscale
---> 46     gray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
     47 
     48     # Get all face from the video frame

error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by nazmiasri95** [comment]
Hey there, it should be okay now. Please use virtual environment, and run `pip install opencv-contrib-python`. That's the only python package needed. Or you can run `pip install -r requirements.txt`
