### ISSUE TITLE
training.py execution failing

### ISSUE THREAD

**Issue by devilmind** [nazmiasri95/Face-Recognition#2]
Hi,
when I run trining.py, I obtain:

`Traceback (most recent call last):
  File "training.py", line 18, in <module>
    recognizer = cv2.face.createLBPHFaceRecognizer()
AttributeError: 'module' object has no attribute 'face'`

I'm using Python 3.4.2 and Opencv 3.1.0

Can you help me pls?

**Comment by sayantandas30011998** [comment]
@devilmind I have the same problem

**Comment by devilmind** [comment]
@sayantandas30011998 issue fixed rebuilding opencv with opencv-contrib module.
