### ISSUE TITLE
error while training the dataset.

### ISSUE THREAD

**Issue by rohitsingh2410** [nazmiasri95/Face-Recognition#3]
![capture](https://user-images.githubusercontent.com/17305828/30631603-a2fcebcc-9d99-11e7-8c65-2c3a6cb26e8d.JPG)
![image](https://user-images.githubusercontent.com/17305828/30631610-a76ecf5e-9d99-11e7-81ad-91d25fcbe69f.png)
Traceback (most recent call last):
  File "D:\facialRecog\project\training.py", line 52, in <module>
    faces,Ids = getImagesAndLabels('dataset')
  File "D:\facialRecog\project\training.py", line 29, in getImagesAndLabels
    pilImage = Image.open(imagePath).convert('L')
  File "C:\Users\Rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: 'dataset\\User'

**Comment by latv** [comment]
be sure the folders name match the folders

**Comment by rohitsingh2410** [comment]
not working bro... 
![not](https://user-images.githubusercontent.com/17305828/34952611-5320cb38-fa40-11e7-9136-5a20397e3993.JPG)

**Comment by nazmiasri95** [comment]
Sorry for the late reply. Please pull the latest code and try whether it's working or not. It does work on my current machine.

Make sure you have right permission to read, write and execute. chmod 777
