### ISSUE TITLE
AttributeError: 'cv2.face_LBPHFaceRecognizer' object has no attribute 'load'

### ISSUE THREAD

**Issue by pi3123** [nazmiasri95/Face-Recognition#4]
AttributeError: 'cv2.face_LBPHFaceRecognizer' object has no attribute 'load'
I get this error all the time, PLS HELP ME!!!!!!

**Comment by medoo2047** [comment]
Just replace recognize.load()
with recognize.read()

**Comment by nazmiasri95** [comment]
Sorry for the late reply. Please pull the latest code and try whether it's working or not. It does work on my current machine.

Yup ! Thanks @medoo2047 for giving the answer. Just replace .load() with .read()

**Comment by parikshitparmar** [comment]
AttributeError: 'cv2.face_LBPHFaceRecognizer' object has no attribute 'predect'

**Comment by 720wof901** [comment]
> o attribu

predict
