### ISSUE TITLE
i got this error,  can u help me?

### ISSUE THREAD

**Issue by wildannajahw** [nazmiasri95/Face-Recognition#5]
gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) cv2.error: /io/opencv/modules/imgproc/src/color.cpp:10638: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by nazmiasri95** [comment]
Hi ! Please pull the latest code and check whether it's working or not. Thanks

**Comment by nazmiasri95** [comment]
I updated the README.md, and I have put requirements.txt for dependencies references
