### ISSUE TITLE
Can you help me with this error

### ISSUE THREAD

**Issue by aakashbhosale007** [nazmiasri95/Face-Recognition#7]
module 'cv2.face' has no attribute 'LBPHFaceRecognizer_create'

**Comment by aakashbhosale007** [comment]
Thanks. It's working now, But now i don't understand how i can get users name in recognition window.  It shows Nazmi on title bar of recognition window.

**Comment by jdeepb** [comment]
module 'cv2.face' has no attribute 'LBPHFaceRecognizer_create'

**Comment by phuttupilot** [comment]
module 'cv2.face' has no attribute 'LBPHFaceRecognizer_create' why does this error is occuring and how do I get rid of this? Please help.

**Comment by nazmiasri95** [comment]
Hey, I have updated the code and put `requirements.txt` for dependencies related problem. Thanks for using this
