### ISSUE TITLE
cant distinguish between two person.

### ISSUE THREAD

**Issue by rohitsingh2410** [nazmiasri95/Face-Recognition#8]
even i've put an if else statement respective to the id number of person whenever two or more then two person comes on camera it labels both of them with a same name.

**Comment by avni88** [comment]
Did you get the solution for this?

**Comment by rohitsingh2410** [comment]
yess

**Comment by avni88** [comment]
How to resolve this issue?

**Comment by nazmiasri95** [comment]
I will look into this problem ASAP
