### ISSUE TITLE
error help??

### ISSUE THREAD

**Issue by jnawotka** [nazmiasri95/Face-Recognition#9]
i am getting this error on the training py file

Traceback (most recent call last):
  File "/home/pi/Face-Recognition/training.py", line 26, in <module>
    recognizer = cv2.face.createLBPHFaceRecognizer()
AttributeError: module 'cv2.cv2' has no attribute 'face'

any idea's

**Comment by treedbox** [comment]
@jnawotka update your opencv:
pip install opencv-contrib-python

**Comment by nazmiasri95** [comment]
Thanks @treedbox , I have updated the README.md and put the `requirements.txt`. Please use virtual environment and use right python package
